spring:
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: yoonseon3@gmail.com # 3
    password: eozy rmaf xmiy jmdj # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7