GET localhost:8080/api/members/1
x-api-version: v1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b29uc2VvbjNAZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcyMjcxMTIzOX0.tJMKVXC8UgCkfHygqdDQxlt_rS-YvXI0l3YQZywyIg82pNis16iH4wE4GU4xkpbSYG2VMUdNHF-aNP-M8zIctg
